### ISSUE TITLE
HTML template error, but dubug does not output the wrong file name, unable to find what file it is

### ISSUE THREAD

**Issue by pianchi** [gofiber/template#92] opened 2021-02-17 12:55 UTC
`views: [Error (where: parser) in <string> | Line 70 Col 62 near '('] '}}' expected`

**Comment by pianchi** [comment] 2021-02-17 12:55
how can i find this error template file?

**Comment by ReneWerner87** [comment] 2021-03-13 10:43
Thanks for the report, what engine are you using ? 
Does the error still occur?

Can you send me the template code so i can investigate ? 
Probably the error is passed on by the underlying engine, i.e. you would have to work on the error output of this engine.

If the problem no longer exists and you(@pianchi ) have no more questions, I would close the issue.

**Comment by ReneWerner87** [comment] 2021-03-19 17:41
Since there is no further message, I assume that the issue is done and can be closed.

if you have any questions, please feel free to open the issue again

**Closed by ReneWerner87** 2021-03-19 17:41 UTC
