### ISSUE TITLE
"malformed record data" when install gogo/protobuf@v1.2.1 

### ISSUE THREAD

**Issue by shar0** [gofiber/template#80] opened 2021-01-02 04:22 UTC
Sample code:
```go
package main

import (
    "strconv"
    "github.com/gofiber/fiber/v2"
    "github.com/gofiber/template/jet"
)

func CustomRoute() *fiber.App {
    engine := jet.New("./views", ".jet")
    route := fiber.New(fiber.Config{
		Views: engine,
	})
    
    route.Get("/sample", func (c *fiber.Ctx) error {
        return c.Render("main", fiber.Map{
			"Title": "Hello, World!",
		})
    })
    return route
}
```

And compile code or use `go mod tidy` will get result:
```
go: github.com/gofiber/template@v1.6.6 requires
        github.com/cbroglie/mustache@v1.2.0 requires
        github.com/golangci/golangci-lint@v1.28.3 requires
        github.com/spf13/viper@v1.7.0 requires
        github.com/gogo/protobuf@v1.2.1/go.mod: verifying module: github.com/gogo/protobuf@v1.2.1/go.mod: malformed record data
```

Is anybody have same issue to me?

**Comment by ReneWerner87** [comment] 2021-03-13 10:05
![image](https://user-images.githubusercontent.com/7063188/111026686-da6c0e80-83eb-11eb-8e50-6ada5413029a.png)

I can't get an error, have you(@shar0 ) found the cause yet? can I close the issue?

**Comment by ReneWerner87** [comment] 2021-03-19 17:42
Since there is no further message, I assume that the issue is done and can be closed.

if you have any questions, please feel free to open the issue again

**Closed by ReneWerner87** 2021-03-19 17:42 UTC
Labels: ♻ Wait for Response, 🔍 Under Investigation
